name: Build InstaMoon APK

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup JDK
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Install Dependencies
        run: sudo apt update && sudo apt install -y zipalign wget rsync curl unzip git

      - name: Give Gradle Execute Permission
        run: chmod +x gradlew

      - name: Build InstaMoon APK
        run: ./gradlew assembleDebug

      - name: Sign APK with Debug Keystore
        run: |
          keytool -genkey -v -keystore debug.keystore -storepass android -keypass android -alias androiddebugkey -keyalg RSA -keysize 2048 -validity 10000 -dname "CN=Android Debug,O=Android,C=US"
          jarsigner -verbose -sigalg SHA1withRSA -digestalg SHA1 \
            -keystore debug.keystore -storepass android \
            -keypass android \
            app/build/outputs/apk/debug/app-debug.apk androiddebugkey

      - name: Optimize APK (Zipalign)
        run: |
          zipalign -v 4 app/build/outputs/apk/debug/app-debug.apk InstaMoon_Aligned.apk

      - name: Upload InstaMoon APK
        uses: actions/upload-artifact@v4
        with:
          name: InstaMoon-APK
          path: InstaMoon_Aligned.apk
