name: Build and Release Instagram Mod

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup JDK
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Install Dependencies
        run: |
          sudo apt update
          sudo apt install -y zipalign wget rsync curl unzip git

      - name: Download APKEditor
        run: |
          wget -O APKEditor.jar "https://github.com/REAndroid/APKEditor/releases/latest/download/APKEditor-1.4.2.jar"

      - name: Download smali & baksmali (Prebuilt)
        run: |
          wget -O smali.jar "https://bitbucket.org/JesusFreke/smali/downloads/smali-2.5.2.jar"
          wget -O baksmali.jar "https://bitbucket.org/JesusFreke/smali/downloads/baksmali-2.5.2.jar"

      - name: Download Instagram APK (base.apk)
        run: |
          wget -O base.apk "https://www.apkmirror.com/wp-content/themes/APKMirror/download.php?id=8322398&key=3a4c0d27d93a9445209dd8dc4c9c97ded521352b&forcebaseapk=true"
       
      - name: Give Execute Permission to Gradle
        run: chmod +x gradlew

      - name: Build InstaMoon APK
        run: ./gradlew assembleDebug

      - name: Create Output Directory
        run: mkdir -p output

      - name: Extract Smali & Resources from InstaMoon
        run: |
          java -jar APKEditor.jar d -i app/build/outputs/apk/debug/app-debug.apk -o output/InstaMoon_Smali

      - name: Decompile Instagram APK
        run: |
          java -jar APKEditor.jar d -i base.apk -o output/Instagram_Smali

      - name: Merge InstaMoon Smali into Instagram
        run: |
          rsync -av output/InstaMoon_Smali/smali/ output/Instagram_Smali/smali/

      - name: Rebuild Modified Instagram APK
        run: |
          java -jar APKEditor.jar b -i output/Instagram_Smali -o output/Instagram_Mod.apk

      - name: Sign APK with Debug Keystore
        run: |
          keytool -genkey -v -keystore debug.keystore -storepass android -keypass android -alias androiddebugkey -keyalg RSA -keysize 2048 -validity 10000 -dname "CN=Android Debug,O=Android,C=US"
          jarsigner -verbose -sigalg SHA1withRSA -digestalg SHA1 \
            -keystore debug.keystore -storepass android \
            -keypass android \
            output/Instagram_Mod.apk androiddebugkey

      - name: Optimize APK (Zipalign)
        run: |
          zipalign -v 4 output/Instagram_Mod.apk output/Instagram_Mod_Aligned.apk

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: v1.0.${{ github.run_number }}
          name: "Instagram Mod Release v1.0.${{ github.run_number }}"
          body: "🚀 New Instagram Mod APK build is ready!"
          files: output/Instagram_Mod_Aligned.apk
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload APK to Bitbucket
        run: |
          curl -X POST -u "${{ secrets.BITBUCKET_USERNAME }}:${{ secrets.BITBUCKET_APP_PASSWORD }}" \
          --form files=@output/Instagram_Mod_Aligned.apk \
          "https://api.bitbucket.org/2.0/repositories/${{ secrets.BITBUCKET_WORKSPACE }}/${{ secrets.BITBUCKET_REPO }}/downloads"

      - name: Send Telegram Notification with Release & Bitbucket Links
        run: |
          GH_RELEASE_LINK="https://github.com/${{ github.repository }}/releases/latest"
          BITBUCKET_LINK="https://bitbucket.org/${{ secrets.BITBUCKET_WORKSPACE }}/${{ secrets.BITBUCKET_REPO }}/downloads/Instagram_Mod_Aligned.apk"

          MESSAGE="🚀 *Modified Instagram APK is ready!* \n\n🔹 [GitHub Release]($GH_RELEASE_LINK) \n🔹 [Bitbucket Download]($BITBUCKET_LINK)"

          curl -s -X POST "https://api.telegram.org/bot${{ secrets.TELEGRAM_BOT_TOKEN }}/sendMessage" \
            -H "Content-Type: application/x-www-form-urlencoded" \
            --data-urlencode "chat_id=${{ secrets.TELEGRAM_CHAT_ID }}" \
            --data-urlencode "text=$MESSAGE" \
            --data-urlencode "parse_mode=Markdown"
